### ISSUE TITLE
Import/Export 

### ISSUE THREAD

**Issue by kzshantonu** [amitmerchant1990/linksnatch#1]
Good stuff. Importing and exporting would be handy I believe

**Comment by arch-user-france1** [comment]
> Good stuff. Importing and exporting would be handy I believe

Open the dev tools, go to storage (firefox) and select localstorage. There it is.

**Comment by arch-user-france1** [comment]
I am not familiar enough with Tailwindcss to just implement a button that would do that. So I probably will not implement it.

**Comment by amitmerchant1990** [comment]
This feature is definitely on my todo list. 👍🏻

**Comment by amitmerchant1990** [comment]
Moved this to discussion https://github.com/amitmerchant1990/linksnatch/discussions/4
