### ISSUE TITLE
Thank you for creating LinkSnatch!

### ISSUE THREAD

**Issue by varunsridharan** [amitmerchant1990/linksnatch#3]
Hi Amit,

I just wanted to reach out and say thank you for creating LinkSnatch. As someone who often finds themselves saving links to read later, I really appreciate the simplicity and ease of use that your app provides. I love that I can save and search links from a single place, and that there are no distractions or unnecessary features getting in the way.

In fact, I found your app so useful that I decided to create a Docker image for it! I've uploaded the image to both GitHub Container Registry and Docker Hub, so anyone can download it and easily spin up an instance of LinkSnatch.

Thank you again for creating such a great tool, and for making it open source so that others can benefit from it as well.

### Docker Hub

> docker run -p 3000:3000 varunsridharan/linksnatch:latest

### Github Container Registry

> docker run -p 3000:3000 ghcr.io/varunsridharan/linksnatch:latest

### Github Repository
> https://github.com/varunsridharan/docker-linksnatch

Best regards,
Varun Sridharan

**Comment by amitmerchant1990** [comment]
Hey @varunsridharan Thanks for contributing and creating the docker version of LinkSnatch. Looks pretty slick!

I have added it in the "Community" section of LinkSnatch's readme. 👍🏻
